//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aquariums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aquariums()
        {
            this.CurrentWorksForFishFarming = new HashSet<CurrentWorksForFishFarming>();
        }
    
        public int IdAquarium { get; set; }
        public string Number { get; set; }
        public int IdFish { get; set; }
        public System.DateTime BoardingDate { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int Quantity { get; set; }
        public double Expenses { get; set; }
        public double Size { get; set; }
        public string Note { get; set; }
    
        public virtual Fish Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentWorksForFishFarming> CurrentWorksForFishFarming { get; set; }
    }
}
