//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetHistory
    {
        public int IdHistory { get; set; }
        public string Name { get; set; }
        public int IdOperation { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TypeOfOperation TypeOfOperation { get; set; }
    }
}
