//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedWorkHistory
    {
        public int IdWorkHistory { get; set; }
        public int IdWorkPlace { get; set; }
        public string Number { get; set; }
        public string ContentName { get; set; }
        public string WorkName { get; set; }
        public System.DateTime DateOfWork { get; set; }
        public string UserSurname { get; set; }
        public string UserName { get; set; }
        public string UserPatronymic { get; set; }
    
        public virtual WorkPlaceForHistory WorkPlaceForHistory { get; set; }
    }
}
