//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentWorksForFishFarming
    {
        public int IdAquarium { get; set; }
        public int IdWork { get; set; }
        public System.DateTime DateOfNextWork { get; set; }
    
        public virtual Aquariums Aquariums { get; set; }
        public virtual ListOfWorksForFishFarming ListOfWorksForFishFarming { get; set; }
    }
}
