//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishWork
    {
        public int IdFish { get; set; }
        public int IdWork { get; set; }
        public int PeriodInDays { get; set; }
    
        public virtual Fish Fish { get; set; }
        public virtual ListOfWorksForFishFarming ListOfWorksForFishFarming { get; set; }
    }
}
