//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvestingHistory
    {
        public int IdHistory { get; set; }
        public int IdPlace { get; set; }
        public string Number { get; set; }
        public string ContentName { get; set; }
        public System.DateTime DateOfHarvest { get; set; }
        public string UserSurname { get; set; }
        public string UserName { get; set; }
        public string UserPatronymic { get; set; }
    
        public virtual PlaceForHistory PlaceForHistory { get; set; }
    }
}
