//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingHistory
    {
        public int IdLandingHistory { get; set; }
        public string FieldNumber { get; set; }
        public string PlantName { get; set; }
        public System.DateTime BoardingDate { get; set; }
        public System.DateTime HarvestDate { get; set; }
        public int FieldSize { get; set; }
        public int HarvestVolume { get; set; }
    }
}
