//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoFarmDBEntities : DbContext
    {
        private static EcoFarmDBEntities _context;
        public static EcoFarmDBEntities GetContext()
        {
            if( _context == null )
                _context = new EcoFarmDBEntities();
            return _context;
        }
        public EcoFarmDBEntities()
            : base("name=EcoFarmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumFish> AlbumFish { get; set; }
        public virtual DbSet<AlbumPlants> AlbumPlants { get; set; }
        public virtual DbSet<Aquariums> Aquariums { get; set; }
        public virtual DbSet<BudgetHistory> BudgetHistory { get; set; }
        public virtual DbSet<CompletedWorkHistory> CompletedWorkHistory { get; set; }
        public virtual DbSet<CurrentWorks> CurrentWorks { get; set; }
        public virtual DbSet<CurrentWorksForFishFarming> CurrentWorksForFishFarming { get; set; }
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<Fish> Fish { get; set; }
        public virtual DbSet<FishWork> FishWork { get; set; }
        public virtual DbSet<HarvestingHistory> HarvestingHistory { get; set; }
        public virtual DbSet<ListOfWorks> ListOfWorks { get; set; }
        public virtual DbSet<ListOfWorksForFishFarming> ListOfWorksForFishFarming { get; set; }
        public virtual DbSet<PlaceForHistory> PlaceForHistory { get; set; }
        public virtual DbSet<Plants> Plants { get; set; }
        public virtual DbSet<PlantWork> PlantWork { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfOperation> TypeOfOperation { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
