//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoFarm.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHistory
    {
        public int IdWorkHistory { get; set; }
        public string FieldNumber { get; set; }
        public string PlantName { get; set; }
        public string WorkName { get; set; }
        public System.DateTime DateOfWork { get; set; }
    }
}
